services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: django-insecure-docker-apenas-para-desenvolvimento
      DJANGO_DEBUG: "True"
      DJANGO_ALLOWED_HOSTS: localhost,127.0.0.1
      SQLITE_PATH: /app/data/db.sqlite3
    volumes:
      - assetflow_data:/app/data

volumes:
  assetflow_data:

