# Generated by Django 5.2.17 on 2026-09-03 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=80)),
                ('identificacao', models.CharField(max_length=40, unique=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('data_retirada', models.DateField()),
                ('data_devolucao', models.DateField(verbose_name='data prevista de devolução')),
                ('finalidade', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='emprestimos.equipamento')),
            ],
            options={
                'verbose_name': 'solicitação de empréstimo',
                'verbose_name_plural': 'solicitações de empréstimo',
                'ordering': ['data_retirada', 'criado_em'],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_devolucao__gte', models.F('data_retirada'))), name='devolucao_igual_ou_apos_retirada')],
            },
        ),
    ]
